export type JournalEntry = {
slug: string;
postmark: string;
dateline: string;
date: string;
category: string;
title: string;
excerpt: string;
readTime: string;
location: string | null;
gym: string | null;
elevation: string | null;
featured: boolean;
destination?: string;
publishDate?: string;
body: { type: string; letter?: string; text: string }[];
};

export const entries: JournalEntry[] = [
{
slug: "bolivia-visa-fight-and-the-pivot",
postmark: "PLAN B",
dateline: "Dallas, Texas",
date: "Aug 19, 2026",
category: "Field Notes",
title: "The plan was Bolivia. The plan changed three days before we left.",
excerpt: "Getting Ginger endorsed for entry and the visa itself turned into an extremely difficult, at times outright rude, process. So we pivoted to Colombia, three days before departure, before either of us ever set foot in an airport.",
readTime: "7 min read",
location: "Dallas, Texas",
gym: null,
elevation: null,
featured: false,
destination: "la-paz",
body: [
{ type: "drop", letter: "T", text: "he plan, for months, was Bolivia. La Paz specifically, altitude training, the whole thing already half written in my head before I ever landed anywhere. I had the gym picked out. I had a rough shape for the journal entries I was going to write about my lungs failing me on day one. I was that far into imagining it." },
{ type: "p", text: "Getting Ginger endorsed for entry, and the visa process itself, turned into something genuinely difficult. Not the normal kind of difficult where you just fill out more forms than you expected. The kind where every phone call felt like it started from a place of no before anyone had even heard what I was asking. Tone matters more than people think it does when you are the one depending on a stranger's willingness to help you, and the tone here was consistently short, dismissive, sometimes outright rude, in a way that started to feel less like bureaucracy and more like a wall that was never going to move no matter how many times I knocked on it." },
{ type: "pull", text: "You can fight a system, or you can go where the door is actually open." },
{ type: "p", text: "I want to be honest that I did try to push through it for longer than probably made sense. There is a version of me that does not like to let a plan die just because it got hard, and I spent real time trying to find the workaround, the right office, the right person, the right day to call back. At some point it stopped being a logistics problem and started being a math problem, days I did not have to keep spending on a country that was not letting me in." },
{ type: "p", text: "So three days before we were supposed to leave, still in Dallas, nowhere near an airport yet, we pivoted. Colombia instead. That decision came with its own scramble, rebooking flights for an extra fee, tracking down an entirely new health certificate for Ginger since Colombia's entry requirements were not the same as Bolivia's, and going back and forth with our original Bolivia Airbnb host for a refund that took far more patience than it should have." },
{ type: "p", text: "None of that part was glamorous. It was three days of phone calls, forms, and a refund request that felt like its own small fight on top of the visa fight I had just walked away from. But it meant that by the time we actually did get on a plane, the plan was already Colombia, not a backup pulled together in a panic at a gate." },
{ type: "p", text: "This page stays up as an honest record of what almost happened, not a guide, since we never actually walked these streets. La Paz was the plan. It just was not the trip. I think there is something worth keeping here about how much of travel, real travel, is actually just this, watching a plan you were emotionally attached to fall apart and choosing to rebuild it from scratch instead of standing still out of loyalty to the version of the trip you already pictured." },
],
},
{
slug: "flying-to-cali-with-ginger",
postmark: "GINGER LOG",
dateline: "Arrival in Cali",
date: "Aug 27, 2026",
category: "Ginger",
title: "What it took to actually get here.",
excerpt: "No food or water for Ginger 14 hours before the flight, a missed connection, and a rebooking that somehow lined up perfectly, landing in Cali just after midnight.",
readTime: "8 min read",
location: "Bogota to Cali",
gym: null,
elevation: null,
featured: false,
destination: "cali",
body: [
{ type: "drop", letter: "I", text: " started prepping Ginger fourteen hours before the flight. No food, no water, starting the night before and holding through most of travel day, which sounds harsher written out than it felt in practice, because she did not know to be upset about it. Dogs do not anticipate a fast the way people do. She just went about her morning a little confused about why breakfast had not shown up, and that was the extent of her protest." },
{ type: "p", text: "At one layover I broke the fast just slightly, a small snack, a little water, enough to take the edge off without undoing the point of the prep in the first place. She took it calmly, more calmly than I expected honestly, more calmly than she takes a car ride to the vet. Something about the stillness of a crate and the low hum of an airport seemed to actually settle her rather than spike her nerves the way I had braced for." },
{ type: "p", text: "Then we missed our connecting flight from Bogota to Cali. Not a delay, not a slow walk through the terminal, it had simply already taken off without us by the time we got to the gate." },
{ type: "pull", text: "We would have been out of luck, except the flight they put us on had already been delayed for hours." },
{ type: "p", text: "There is a very specific kind of panic that shows up when you are standing at a gate that has already closed, doing rapid math on hotel costs and whether your dog's paperwork is even valid for an unplanned overnight in a city you were not supposed to be sleeping in. I felt that panic fully, for about the length of time it took the gate agent to look up and tell me they had another flight leaving in an hour." },
{ type: "p", text: "The replacement flight was the lucky part. It had actually been sitting there delayed for hours already, grounded because of a technical issue, originally supposed to have left long before we ever showed up. If everything had gone according to the original schedule, it would have taken off without us too, same as the first one. Instead its own problems meant it was still on the ground exactly when we needed it to be, and we walked straight onto a flight that, on paper, should not have still been there." },
{ type: "p", text: "So we got on it, and somewhere in the descent into Cali I stopped being angry about the missed connection and started being grateful for a delay that had nothing to do with us but ended up saving the whole day. We landed, cleared everything, and made it to our first Airbnb in Cali just after midnight on the 27th. Ginger walked into that apartment and immediately did a full perimeter check of every room, nose down, tail up, like she was clocking in for a job she took very seriously. Exhausted, completely off the original plan, but there, both of us, in one piece." },
],
},
{
slug: "chinchina-teaching-trip",
postmark: "CHINCHINA",
dateline: "Chinchina, Colombia",
date: "Aug 29, 2026",
category: "Culture",
title: "A few days in Chinchina, cut shorter than planned.",
excerpt: "A few days after landing in Cali, we traveled to Chinchina to teach. Unforeseen circumstances brought us back to Cali earlier than expected.",
readTime: "5 min read",
location: "Chinchina, Colombia",
gym: null,
elevation: null,
featured: false,
destination: "cali",
body: [
{ type: "drop", letter: "A", text: " few days after we landed in Cali, we traveled to Chinchina to teach. This was the part of the trip I had actually planned for on purpose, unlike almost everything that came before it. Chinchina sits up in coffee country, greener and cooler than Cali, the kind of place where the air itself smells faintly like the region's biggest export before you even see a single coffee plant." },
{ type: "p", text: "Teaching there felt different than teaching has felt anywhere else I have done it. There was an openness to the people showing up that I was not fully prepared for, the kind of curiosity that makes a room easy to stand in front of. I had one of those mornings that reminds you why you keep signing up to do this in the first place, even on the days abroad feel harder than staying home would have been." },
{ type: "p", text: "Unforeseen circumstances meant we ended up heading back to Cali earlier than expected. I am keeping the specifics loose here on purpose, some of it is still unfolding and not fully mine to lay out in detail yet, but the short version is honest enough, the trip got cut shorter than planned, and we adjusted." },
{ type: "p", text: "What did not get cut short was the one afternoon that mattered most, which gets its own entry, because it deserves one on its own rather than getting folded into the footnotes of a trip that ended early." },
],
},
{
slug: "villamaria-tunnels-and-the-waterfall",
postmark: "FIELD TRIP",
dateline: "Villamaria, Colombia",
date: "Aug 30, 2026",
category: "Travel",
title: "The hike that almost did not happen.",
excerpt: "The original route fell through at the last minute. What we got instead, the tunnels of Villamaria, a waterfall, and Ginger swimming, ended up being the better version anyway.",
readTime: "6 min read",
location: "Villamaria, Colombia",
gym: null,
elevation: null,
featured: true,
destination: "cali",
body: [
{ type: "drop", letter: "T", text: "he original plan was a route called La Reina, and it fell through entirely, one of those trip cancellations with no real explanation attached, just a message saying it was not happening. In its place, a group chat lit up with a last-minute offer instead, an announcement in Spanish that read almost like a dare, nature, water, history, and views, at the tunnels of Villamaria, leaving from Chinchina at 8am, back by 4pm, only five spots available, and a line at the end that stuck with me, something like do not stay home while everyone else is living the adventure." },
{ type: "p", text: "We took one of the five spots." },
{ type: "pull", text: "Do not stay home while everyone else is living the adventure." },
{ type: "p", text: "The tunnels themselves were carved through hillside that felt older than anything I have walked through in a long time, cool and damp in a way that made the heat outside feel like a different climate entirely once you stepped back out of them. The hike wound through green so dense it swallowed the trail edges, and every turn seemed to promise a view that the next turn actually delivered." },
{ type: "p", text: "Then the waterfall showed up, and it was the kind you do not quite believe is real until you are standing close enough to feel the spray on your face. Ginger had been trotting along the whole hike with the specific energy of a dog who knows something good is coming, and the moment she saw the water she did not hesitate for a second. She swam, off leash, fully thrilled, in a way she has not really gotten to be since this trip started. Watching her move through that water like she had done it a hundred times before was worth more to me than the hike itself." },
{ type: "p", text: "It was supposed to be a backup plan for a route that did not happen. It ended up being one of the best afternoons of the entire trip so far, and a good reminder that the thing you get instead of the thing you planned is sometimes just better." },
],
},
{
slug: "navigating-gingers-heat-abroad",
postmark: "GINGER LOG",
dateline: "Cali, Colombia",
date: "Sept 2, 2026",
category: "Ginger",
title: "She started her heat the same day we got on the plane.",
excerpt: "Diapers, a romper, and a lot of vigilance, what it actually takes to protect an unspayed dog through her heat cycle in a country full of loose, unneutered street dogs.",
readTime: "7 min read",
location: "Cali, Colombia",
gym: null,
elevation: null,
featured: false,
destination: "cali",
body: [
{ type: "drop", letter: "G", text: "inger started her heat the same day we got on the plane to leave Dallas. Of all the days for her body to pick, that was the one, right as we were headed into the country with the least predictable dog population of the entire trip so far." },
{ type: "p", text: "Cali is full of strays and outdoor dogs, roaming loose in a way that is completely normal here and completely different from what I am used to managing at home. Most of them are not neutered. A dog in heat, walked openly through that environment, is basically broadcasting her exact situation to every intact male within scent range, and scent range for an unspayed female is a lot farther than people think." },
{ type: "pull", text: "Protecting her here meant treating every walk like a small operation, not a stroll." },
{ type: "p", text: "The setup became a dog diaper underneath and a romper over it, both at once, not one or the other. The diaper handles the obvious mess and, more importantly, cuts down significantly on how much scent actually gets out into the air as she moves. The romper does double duty, it holds the diaper securely in place so she cannot wriggle out of it mid-walk the way dogs love to try, and it adds one more physical barrier on top in case any male dog gets bold enough to try something despite the diaper." },
{ type: "p", text: "I got more careful about timing too, walking her at hours when the street dog traffic in our area tended to be lighter, keeping her closer on leash than usual instead of letting her have her normal roaming radius, and staying alert in a way that made every walk feel a little more like work than it used to. Watching her body language became constant, the second she tensed or a strange dog's head snapped toward us from across the street, I was already moving her the other direction." },
{ type: "p", text: "None of it stopped her from being herself. She still wanted to sniff everything, still wanted to say hello to every dog we passed, heat or no heat, and the hardest part honestly was being the one to keep saying no on her behalf for her own safety, in a city she is still learning the rules of. It has been a genuine crash course in traveling with an intact female dog somewhere strays outnumber leashed dogs, and I would rather write down exactly what worked here than pretend it was not a real adjustment." },
],
},
{
slug: "mundo-peludo-grooming-cali",
postmark: "GINGER APPROVED",
dateline: "Cali, Colombia",
date: "Sept 5, 2026",
category: "Ginger",
title: "Ginger's first groom in Colombia, and it was a great one.",
excerpt: "Peluqueria Canina Mundo Peludo in Nueva Granada gave Ginger her first grooming appointment of the trip, and it earns a real spot on the Ginger Approved list.",
readTime: "4 min read",
location: "Nueva Granada, Cali",
gym: null,
elevation: null,
featured: false,
destination: "cali",
body: [
{ type: "drop", letter: "G", text: "inger's coat needed real attention after everything the last couple weeks had thrown at her, a flight, a hike through a waterfall, and general life on the road, so finding somewhere trustworthy to take a standard poodle for a proper groom in a new country was not something I wanted to leave to chance." },
{ type: "p", text: "Peluqueria Canina Mundo Peludo, tucked into Nueva Granada on Carrera 38c, ended up being exactly that. The appointment was a genuinely great experience from start to finish, the kind of visit that makes you relax a little about the whole logistics of keeping a high-maintenance coat looking decent while living out of bags in a different country every few weeks." },
{ type: "pull", text: "A great groom abroad is worth writing down, because finding one is half the battle." },
{ type: "p", text: "Ginger came out looking and smelling like herself again, coat properly maintained, clearly comfortable the whole time rather than stressed the way a new place with new hands on her could easily have gone. That matters more than people realize, a standard poodle who has a bad first grooming experience in a new country can turn skittish about every appointment after it, and this was the opposite of that." },
{ type: "p", text: "This one earns a real spot on the Ginger Approved list, not a placeholder. If you are traveling through Cali with a dog that needs real grooming, not just a bath, Mundo Peludo is where I would send you." },
],
},
{
slug: "stopped-waiting-for-right-time",
postmark: "FIELD NOTES",
dateline: "Dallas, Texas",
date: "April 3, 2026",
category: "Field Notes",
title: "Why I stopped waiting for the \"right time\"",
excerpt: "Every plan I made had a reason to wait one more season. This is the entry about the season I stopped listening to that reason.",
readTime: "6 min read",
location: null,
gym: null,
elevation: null,
featured: false,
body: [
{ type: "drop", letter: "E", text: "very plan I made had a reason to wait one more season. I did everything right, the degree, the internships, and I landed a psych job right out of college that felt like proof the plan was working. Then the company shut down, part of a wave of federal-adjacent cuts under the new administration, and the job I had built my whole next five years around was just gone." },
{ type: "p", text: "Moving back home was supposed to be temporary, a way to save money before signing another lease I could barely afford alone. My aunt was the one who told me my parents said I was welcome back. Not my parents. My aunt, relaying it secondhand, which should have told me something already." },
{ type: "p", text: "It did not take long to remember why I left the first time. Welcome came with terms nobody said out loud until I broke one. I got called slurs for who I love, in my own childhood bedroom, by the people who were supposed to protect me from exactly that. When I finally found the nerve to say it hurt, to ask for something different, I was told I was too sensitive, too dramatic, too much. My feelings got returned to sender every time I tried to send them." },
{ type: "pull", text: "Welcome, but only on their terms." },
{ type: "p", text: "So I stopped asking to be understood there and started building somewhere I could be. I did not tell anyone the real departure date, not friends, not extended family, nobody. I let people believe I was still figuring it out until I had already landed. Where I come from, you do not hand your good news to just anyone before it is real. Not every set of eyes wishes you well, and I was not about to let mal de ojo have a shot at something I had fought this hard for." },
{ type: "p", text: "This is the entry about the season I stopped listening to the voice that said wait. Nothing dramatic triggered it in the end, just the slow realization that the people I was waiting to finally see me were never going to. So I picked a date, told almost no one, and let the plane ticket do what four years of asking never could." },
],
},
];
