export const entries = [
{
slug: "altitude-ego-first-sparring",
postmark: "LA PAZ BOL.",
dateline: "La Paz, Bolivia",
date: "Aug 24, 2026",
category: "Training",
title: "Altitude, ego, and the first sparring round",
excerpt: "At 3,600 meters, everything you thought you knew about your own conditioning gets rewritten in the first ninety seconds. This is the entry where I admit that.",
readTime: "6 min read",
location: "Los Pinos, La Paz",
gym: "Altitud MMA and BJJ",
elevation: "3,600m",
featured: true,
destination: "la-paz",
publishDate: "2026-08-26",
body: [
{ type: "drop", letter: "A", text: "t 3,600 meters, everything you thought you knew about your own conditioning gets rewritten in the first ninety seconds. I walked into Altitud MMA and BJJ on day four, still telling myself the altitude thing was overblown. It was not overblown." },
{ type: "p", text: "The gym itself is unassuming from the street, a converted space in Los Pinos with mats that have clearly seen a decade of use. Inside, it is exactly what you would hope for, no attitude, no gatekeeping, just people showing up to work. I got paired with someone half my size who had grown up training at this exact elevation, and within the first exchange I understood the gap between fit and fit here." },
{ type: "pull", text: "The air doesn't care how many rounds you've gone at sea level." },
{ type: "p", text: "By the third minute my hands were on my knees between exchanges, which has not happened to me in years. There is a specific kind of humility that comes from your body simply not being able to do what your brain is asking of it, not from lack of skill, just lack of oxygen. I tapped twice in that first round, both times from gas, not technique." },
{ type: "p", text: "What surprised me more than the physical reset was the mental one. I have spent years building an identity around being the one who doesn't get tired, doesn't ask for a breather, pushes through. La Paz doesn't let you keep that story. Everyone here trains slower, more deliberately, with longer rests between rounds, because the alternative is passing out. It is not weakness, it is just physics." },
{ type: "p", text: "I will be back on the mats three times a week for the rest of this stay. Not because I have adjusted yet, but because the only way through this kind of humbling is more of it." },
],
},
{
slug: "flying-with-standard-poodle",
postmark: "GINGER LOG",
dateline: "Arrival in La Paz",
date: "Aug 22, 2026",
category: "Ginger",
title: "What it actually takes to fly with a standard poodle",
excerpt: "The paperwork, the vet visits, the 4am crate training, a full accounting of what nobody tells you before your dog becomes your travel partner.",
readTime: "5 min read",
location: "Dallas to La Paz",
gym: null,
elevation: null,
featured: false,
publishDate: "2026-08-22",
body: [
{ type: "drop", letter: "T", text: "he paperwork started three months before departure. Health certificates, vaccine records, a specific USDA form that has to be signed within ten days of travel, not a day earlier. I learned that the hard way, redoing the whole process once because I filed too soon." },
{ type: "p", text: "Then there was the crate training. Ginger is not a small dog, and getting a standard poodle comfortable in an airline-approved crate for the first time takes weeks, not days. We started with the door open in the living room, treats inside, no pressure. By week three she was sleeping in it voluntarily." },
{ type: "p", text: "The 4am wake-up on departure day was its own kind of chaos, but by the time we landed in La Paz, she was calmer than I was." },
],
},
{
slug: "stopped-waiting-for-right-time",
postmark: "FIELD NOTES",
dateline: "Dallas, Texas",
date: "April 3, 2026",
category: "Field Notes",
title: "Why I stopped waiting for the \"right time\"",
excerpt: "Every plan I made had a reason to wait one more season. This is the entry about the season I stopped listening to that reason.",
readTime: "6 min read",
location: null,
gym: null,
elevation: null,
featured: false,
body: [
{ type: "drop", letter: "E", text: "very plan I made had a reason to wait one more season. I did everything right, the degree, the internships, and I landed a psych job right out of college that felt like proof the plan was working. Then the company shut down, part of a wave of federal-adjacent cuts under the new administration, and the job I had built my whole next five years around was just gone." },
{ type: "p", text: "Moving back home was supposed to be temporary, a way to save money before signing another lease I could barely afford alone. My aunt was the one who told me my parents said I was welcome back. Not my parents. My aunt, relaying it secondhand, which should have told me something already." },
{ type: "p", text: "It did not take long to remember why I left the first time. Welcome came with terms nobody said out loud until I broke one. I got called slurs for who I love, in my own childhood bedroom, by the people who were supposed to protect me from exactly that. When I finally found the nerve to say it hurt, to ask for something different, I was told I was too sensitive, too dramatic, too much. My feelings got returned to sender every time I tried to send them." },
{ type: "pull", text: "Welcome, but only on their terms." },
{ type: "p", text: "So I stopped asking to be understood there and started building somewhere I could be. I did not tell anyone the real departure date, not friends, not extended family, nobody. I let people believe I was still figuring it out until I had already landed. Where I come from, you do not hand your good news to just anyone before it is real. Not every set of eyes wishes you well, and I was not about to let mal de ojo have a shot at something I had fought this hard for." },
{ type: "p", text: "This is the entry about the season I stopped listening to the voice that said wait. Nothing dramatic triggered it in the end, just the slow realization that the people I was waiting to finally see me were never going to. So I picked a date, told almost no one, and let the plane ticket do what four years of asking never could." },
],
},
];
